name: Link Checker

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    - cron: '0 0 * * 1' # Run every Monday at midnight

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true

    - name: Build site
      run: bundle exec jekyll build

    - name: List _site content (Debug)
      run: ls -R _site | head -n 50

    - name: Check links
      run: |
        bundle exec htmlproofer ./_site \
          --allow-hash-href \
          --check-html \
          --report-invalid-tags \
          --report-missing-names \
          --report-script-embeds \
          --report-missing-doctype \
          --report-eof-tags \
          --report-mismatched-tags \
          --check-opengraph \
          --disable-external \
          --url-ignore "/{{site.baseurl}}{% post_url .*%}/,/https://www.linkedin.com/in/lukasvermeer/,/http://www.xebicon.nl/,/http://www.einarsen.no/,/http://www.dangardner.ca/,/http://www.cyanogenmod.com/,/http://www.cornify.com/,/http://wiki.cyanogenmod.com/,/http://wiki.answers.com/,/http://wiki.allshadow.com/,/http://unix.derkeiler.com/,/http://theunlockr.com/,/http://stevehanov.ca/,/http://shape-of-code.coding-guidelines.com/,/http://lukazz.livejournal.com/,/http://laudy.net/,/http://konamicodesites.com/,/http://jtonedm.com/,/http://ieet.org/,/http://ide.mit.edu/,/http://download.cnet.com/,/http://datafun.eventbrite.com/,/http://connectfourservice.appspot.com/,/http://businessintelligence.com/,/http://bigthink.com/" \
          --enforce-https \
          --alt-ignore "/.*/"
